name: Build AutoRemesher for macOS

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Tag name for release
        required: true

permissions:
  contents: write

jobs:
  build-mac:
    name: Build AutoRemesher for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: NONINTERACTIVE=1 arch --x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: arch --x86_64 /usr/local/Homebrew/bin/brew install boost c-blosc cgal cmake gcc make mpfr openvdb qt tbb zlib || true # This returns exit code 1 even if successful - why ??
      - run: ./build-mac.sh
      - run: find $HOME/autoremesher/autoremesher.app -name .DS_Store -delete
      - run: ditto -c -k --sequesterRsrc --keepParent $HOME/autoremesher/autoremesher.app $HOME/autoremesher-${{ github.event.inputs.tagName }}-mac.zip
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          files: $HOME/autoremesher-${{ github.event.inputs.tagName }}-mac.zip
